version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo installing source NPM dependencies..
      - npm install
  build:
     commands:
     - echo Build started on `date`
     - echo building the Node.js application..
     - npm install
  post _build:
    commands:
      - echo build completed on `date`
      - mkdir deploy
      - cp -r dist deploy/dist
      - mv appspec.yaml appspec.yml
      - cp appspec.yml deploy/
      - cp -r script deploy/
      - chmod +x deploy/script/restartnginx.sh
      - chmod +x deploy/script/appStop.sh

artifacts:
  files:
    - '**/*'
  base-directory: deploy
  name: frontend-build
